"""init

Revision ID: 13e85a652e62
Revises: 
Create Date: 2026-02-20 13:44:56.219519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13e85a652e62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono_url', sa.String(length=255), nullable=True),
    sa.Column('condicion_tipo', sa.String(length=50), nullable=True),
    sa.Column('condicion_valor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_icfes', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono_url', sa.String(length=255), nullable=True),
    sa.Column('color_hex', sa.String(length=10), nullable=True),
    sa.Column('esta_activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('rol', sa.Enum('estudiante', 'profesor', 'admin_contenido', 'admin_tech', name='rol_usuario'), nullable=False),
    sa.Column('es_premium', sa.Boolean(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('racha_actual', sa.Integer(), nullable=False),
    sa.Column('racha_maxima', sa.Integer(), nullable=False),
    sa.Column('puntos_totales', sa.Integer(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_acceso', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=10), nullable=True),
    sa.Column('esta_activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aulas_codigo_acceso'), 'aulas', ['codigo_acceso'], unique=True)
    op.create_index(op.f('ix_aulas_id'), 'aulas', ['id'], unique=False)
    op.create_index(op.f('ix_aulas_profesor_id'), 'aulas', ['profesor_id'], unique=False)
    op.create_table('avatares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('animal_base', sa.String(length=50), nullable=True),
    sa.Column('accesorio_sombrero', sa.String(length=50), nullable=True),
    sa.Column('accesorio_gafas', sa.String(length=50), nullable=True),
    sa.Column('color_primario', sa.String(length=10), nullable=True),
    sa.Column('color_secundario', sa.String(length=10), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('estadisticas_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('total_respondidas', sa.Integer(), nullable=False),
    sa.Column('total_correctas', sa.Integer(), nullable=False),
    sa.Column('porcentaje_acierto', sa.Integer(), nullable=False),
    sa.Column('ultima_sesion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=False
    )
    op.create_table('logs_actividad',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_actividad_usuario_id'), 'logs_actividad', ['usuario_id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('reto', 'meta_diaria', 'nuevo_contenido', 'racha', 'sistema', name='tipo_notificacion'), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('dato_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creada_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('creada_por', sa.Integer(), nullable=True),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.Enum('opcion_multiple', 'lectura_critica', 'matematica', name='tipo_pregunta'), nullable=False),
    sa.Column('nivel_dificultad', sa.Enum('facil', 'medio', 'dificil', name='nivel_dificultad'), nullable=False),
    sa.Column('competencia', sa.String(length=100), nullable=True),
    sa.Column('explicacion_texto', sa.Text(), nullable=True),
    sa.Column('veces_respondida', sa.Integer(), nullable=False),
    sa.Column('veces_incorrecta', sa.Integer(), nullable=False),
    sa.Column('esta_activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preguntas_id'), 'preguntas', ['id'], unique=False)
    op.create_index(op.f('ix_preguntas_materia_id'), 'preguntas', ['materia_id'], unique=False)
    op.create_table('sesiones_juego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modo_juego', sa.Enum('libre', 'arcade', 'contrarreloj', 'online_tradicional', 'online_poderes', 'online_arcade', name='modo_juego'), nullable=False),
    sa.Column('puntaje_obtenido', sa.Integer(), nullable=False),
    sa.Column('total_preguntas', sa.Integer(), nullable=True),
    sa.Column('total_correctas', sa.Integer(), nullable=False),
    sa.Column('pistas_usadas', sa.Integer(), nullable=False),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalizada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_juego_id'), 'sesiones_juego', ['id'], unique=False)
    op.create_index(op.f('ix_sesiones_juego_usuario_id'), 'sesiones_juego', ['usuario_id'], unique=False)
    op.create_table('suscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'premium', 'premium_profesor', name='plan_suscripcion'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('esta_activa', sa.Boolean(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('referencia_pago', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens_recuperacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('usuario_logros',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('logro_id', sa.Integer(), nullable=False),
    sa.Column('obtenido_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logro_id'], ['logros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'logro_id')
    )
    op.create_table('aula_estudiantes',
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('fecha_union', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aula_id', 'estudiante_id')
    )
    op.create_table('opciones_respuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('letra', sa.String(length=1), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opciones_respuesta_pregunta_id'), 'opciones_respuesta', ['pregunta_id'], unique=False)
    op.create_table('partidas_online',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador1_id', sa.Integer(), nullable=False),
    sa.Column('jugador2_id', sa.Integer(), nullable=True),
    sa.Column('sesion_j1_id', sa.Integer(), nullable=True),
    sa.Column('sesion_j2_id', sa.Integer(), nullable=True),
    sa.Column('ganador_id', sa.Integer(), nullable=True),
    sa.Column('modo', sa.Enum('tradicional', 'poderes', 'arcade', name='modo_partida'), nullable=False),
    sa.Column('estado', sa.Enum('buscando', 'en_curso', 'finalizada', 'cancelada', name='estado_partida'), nullable=False),
    sa.Column('creada_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ganador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jugador1_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jugador2_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sesion_j1_id'], ['sesiones_juego.id'], ),
    sa.ForeignKeyConstraint(['sesion_j2_id'], ['sesiones_juego.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_online_id'), 'partidas_online', ['id'], unique=False)
    op.create_table('pistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('texto_pista', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Enum('semanal', 'mensual', name='periodo_ranking'), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio_periodo', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aula_id', 'usuario_id', 'periodo', 'fecha_inicio_periodo', name='uq_ranking_periodo')
    )
    op.create_index(op.f('ix_ranking_aula_aula_id'), 'ranking_aula', ['aula_id'], unique=False)
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('error_contenido', 'error_tecnico', 'respuesta_incorrecta', 'imagen_rota', 'otro', name='tipo_reporte'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_revision', 'resuelto', 'descartado', name='estado_reporte'), nullable=False),
    sa.Column('resuelto_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.ForeignKeyConstraint(['resuelto_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poderes_partida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_poder', sa.String(length=50), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('usado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas_online.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('opcion_elegida_id', sa.Integer(), nullable=True),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('uso_pista', sa.Boolean(), nullable=False),
    sa.Column('solicito_ia', sa.Boolean(), nullable=False),
    sa.Column('tiempo_respuesta_ms', sa.Integer(), nullable=True),
    sa.Column('respondida_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opcion_elegida_id'], ['opciones_respuesta.id'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_juego.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respuestas_usuario_pregunta_id'), 'respuestas_usuario', ['pregunta_id'], unique=False)
    op.create_index(op.f('ix_respuestas_usuario_sesion_id'), 'respuestas_usuario', ['sesion_id'], unique=False)
    op.create_table('retos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retador_id', sa.Integer(), nullable=False),
    sa.Column('retado_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=True),
    sa.Column('partida_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aceptado', 'rechazado', 'expirado', name='estado_reto'), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas_online.id'], ),
    sa.ForeignKeyConstraint(['retado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['retador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retos')
    op.drop_index(op.f('ix_respuestas_usuario_sesion_id'), table_name='respuestas_usuario')
    op.drop_index(op.f('ix_respuestas_usuario_pregunta_id'), table_name='respuestas_usuario')
    op.drop_table('respuestas_usuario')
    op.drop_table('poderes_partida')
    op.drop_table('reportes')
    op.drop_index(op.f('ix_ranking_aula_aula_id'), table_name='ranking_aula')
    op.drop_table('ranking_aula')
    op.drop_table('pistas')
    op.drop_index(op.f('ix_partidas_online_id'), table_name='partidas_online')
    op.drop_table('partidas_online')
    op.drop_index(op.f('ix_opciones_respuesta_pregunta_id'), table_name='opciones_respuesta')
    op.drop_table('opciones_respuesta')
    op.drop_table('aula_estudiantes')
    op.drop_table('usuario_logros')
    op.drop_table('tokens_recuperacion')
    op.drop_table('suscripciones')
    op.drop_index(op.f('ix_sesiones_juego_usuario_id'), table_name='sesiones_juego')
    op.drop_index(op.f('ix_sesiones_juego_id'), table_name='sesiones_juego')
    op.drop_table('sesiones_juego')
    op.drop_index(op.f('ix_preguntas_materia_id'), table_name='preguntas')
    op.drop_index(op.f('ix_preguntas_id'), table_name='preguntas')
    op.drop_table('preguntas')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_logs_actividad_usuario_id'), table_name='logs_actividad')
    op.drop_table('logs_actividad')
    op.drop_table('estadisticas_usuario')
    op.drop_table('avatares')
    op.drop_index(op.f('ix_aulas_profesor_id'), table_name='aulas')
    op.drop_index(op.f('ix_aulas_id'), table_name='aulas')
    op.drop_index(op.f('ix_aulas_codigo_acceso'), table_name='aulas')
    op.drop_table('aulas')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('materias')
    op.drop_table('logros')
    # ### end Alembic commands ###
