"""add_textos_fix_preguntas

Revision ID: 672633936a1e
Revises: 13e85a652e62
Create Date: 2026-03-02 13:41:48.641067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672633936a1e'
down_revision: Union[str, None] = '13e85a652e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('textos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fuente', sa.String(length=255), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('opciones_respuesta', 'imagen_url')
    op.drop_column('opciones_respuesta', 'letra')
    op.add_column('preguntas', sa.Column('texto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'preguntas', 'textos', ['texto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preguntas', type_='foreignkey')
    op.drop_column('preguntas', 'texto_id')
    op.add_column('opciones_respuesta', sa.Column('letra', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.add_column('opciones_respuesta', sa.Column('imagen_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('textos')
    # ### end Alembic commands ###
