"""add imagen_url to opciones_respuesta

Revision ID: dc171e7d524a
Revises: e2f3a4b5c6d7
Create Date: 2026-04-06 13:11:25.754536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc171e7d524a"
down_revision: Union[str, None] = "e2f3a4b5c6d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulacro_sesiones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "activo",
                "pausado",
                "entre_bloques",
                "completado",
                name="estado_simulacro",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("bloque_actual", sa.Integer(), nullable=False),
        sa.Column("limite_bloque1", sa.Integer(), nullable=False),
        sa.Column("preguntas_ids", sa.Text(), nullable=False),
        sa.Column("respuestas", sa.Text(), nullable=False),
        sa.Column("indice_actual", sa.Integer(), nullable=False),
        sa.Column("tiempo_restante_b1_seg", sa.Integer(), nullable=False),
        sa.Column("tiempo_restante_b2_seg", sa.Integer(), nullable=False),
        sa.Column(
            "iniciada_en",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completada_en", sa.DateTime(), nullable=True),
        sa.Column("ultimo_guardado_en", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulacro_sesiones_id"), "simulacro_sesiones", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_simulacro_sesiones_usuario_id"),
        "simulacro_sesiones",
        ["usuario_id"],
        unique=False,
    )
    op.add_column(
        "opciones_respuesta",
        sa.Column("imagen_url", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opciones_respuesta", "imagen_url")
    op.drop_index(
        op.f("ix_simulacro_sesiones_usuario_id"), table_name="simulacro_sesiones"
    )
    op.drop_index(op.f("ix_simulacro_sesiones_id"), table_name="simulacro_sesiones")
    op.drop_table("simulacro_sesiones")
    # ### end Alembic commands ###
