"""add imagen_src to avatares

Revision ID: ea1777ad591a
Revises: 672633936a1e
Create Date: 2026-03-08 15:13:18.581518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1777ad591a'
down_revision: Union[str, None] = '672633936a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatares', sa.Column('imagen_src', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatares', 'imagen_src')
    # ### end Alembic commands ###
