"""remove color columns from avatares

Revision ID: fce63bd4729b
Revises: b06735295122
Create Date: 2026-03-31 15:28:41.222175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce63bd4729b'
down_revision: Union[str, None] = 'b06735295122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatares', 'color_primario')
    op.drop_column('avatares', 'color_secundario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatares', sa.Column('color_secundario', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('avatares', sa.Column('color_primario', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
